### ISSUE TITLE
OpenCVSharp error on Mac 

### ISSUE THREAD

**Issue by Francegala** [yukihiko/ThreeDPoseUnitySample#18]
Hello @yukihiko
Would it be possible a quick guide on how to run this project, please?
I am moving my first steps into this field and I would like to learn more. I tried to run it but I receive the errors below.
My system:
MacBook Pro (16-inch, 2019)
2.6 GHz 6-Core Intel Core i7
32 GB 2667 MHz DDR4
AMD Radeon Pro 5500M 8 GB
Unity 2019 4 12 f1

What are the requirements to make it run? any prerequisites?

![image](https://user-images.githubusercontent.com/7479492/96347715-77c05200-109b-11eb-8460-c6d8877c4f4b.png)

![image](https://user-images.githubusercontent.com/7479492/96347718-7d1d9c80-109b-11eb-87bd-2892bff41beb.png)

**Comment by yukihiko** [comment]
OpenCVSharp is for Windows PC. Maybe it won't work on Mac

**Comment by Francegala** [comment]
I confirm, it works on Windows
