### ISSUE TITLE
Compute joint's rotation from joint's position

### ISSUE THREAD

**Issue by imbinwang** [yukihiko/ThreeDPoseUnitySample#5]
Thanks for your impressive work.

I am insterested in computing joint's rotation from the joint's position and its child joint's position. As far as I understand it, it is hard to recover the rotation alone bone direction when just bone directions of current frame and initial frame are given.

Your solution is as follows, 
`jointPoint.Transform.rotation = Quaternion.LookRotation(jointPoint.Pos3D - jointPoint.Child.Pos3D, forward) * jointPoint.Inverse * jointPoint.InitRotation; `
and the `jointPoint.Inverse` is the initial rotation quaternion from joint's bone direction. I notice that the `jointPoint.Inverse` is computed using default up-vector while here the current forward vector is used. Could you give a description please? Any other blog or tutorial would be appreciated.

**Comment by yukihiko** [comment]
Thank you.

As you pointed out, here we are just calculating how much it has rotated from its initial value.
The page I referred to was 404.

Certainly, Inverse's calculation
private quaternion GetInverse (JointPoint p1, JointPoint p2, Vector3 forward)
{
return Quaternion.Inverse (Quaternion.LookRotation (p1.Transform.position-p2.Transform.position, forward));
}
It might be better to do like this.

**Comment by imbinwang** [comment]
I got it. Thank you.
