### ISSUE TITLE
Any guidline to create other 3d model like Unity-chan in the sample?

### ISSUE THREAD

**Issue by peterchen2001** [yukihiko/ThreeDPoseUnitySample#6]
Great work! Is there any guidline or rules to create other 3d model like Unity-chan in the sample? i want to change the model to other ones, such as a man, a policeman, etc.

**Comment by yukihiko** [comment]
Thank you.

I think that it works if there is bones used in the code.
GameObject is added to the position of the nose. It is used to determine the orientation of the face. I added GameObjects to ears etc, but I don't think I used them anymore.

**Comment by peterchen2001** [comment]
Thanks for your quick reply!
